export const vehicleArray = [
  { id: 0, image: require('../assets/img/airplane.png'), name: '비행기' },
  { id: 1, image: require('../assets/img/bicycle.png'), name: '자전거' },
  { id: 2, image: require('../assets/img/bus.png'), name: '버스' },
  { id: 3, image: require('../assets/img/car.png'), name: '차' },
  { id: 4, image: require('../assets/img/cruise.png'), name: '크루즈' },
  { id: 5, image: require('../assets/img/ship.png'), name: '여객선' },
  { id: 6, image: require('../assets/img/subway.png'), name: '지하철' },
  { id: 7, image: require('../assets/img/train.png'), name: '기차' },
  { id: 8, image: require('../assets/img/walk.png'), name: '도보' },
];

export const activities = [
  { id: 1, name: '등산' },
  { id: 2, name: '캠핑' },
  { id: 3, name: '낚시' },
  { id: 4, name: '천체 관측' },
  { id: 5, name: '자전거' },
  { id: 6, name: '피크닉' },
  { id: 7, name: '수영' },
  { id: 8, name: '수상 스포츠' },
  { id: 9, name: '겨울 스포츠' },
  { id: 10, name: '관광지' },
  { id: 11, name: '맛집' },
  { id: 12, name: '쇼핑' },
  { id: 13, name: '축제' },
  { id: 14, name: '공연 관람' },
  { id: 15, name: '사진 촬영' },
  { id: 16, name: '마사지' },
  { id: 17, name: '온천/찜질방' },
  { id: 18, name: '리조트' },
  { id: 19, name: '스포츠 관람' },
  { id: 20, name: '봉사활동' },
  { id: 21, name: '유학' },
  { id: 22, name: '가족 여행' },
  { id: 23, name: '크루즈' },
];
